import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Features from '../components/features/features'
import Footer from '../components/footer/footer'
import Initial from '../components/intial/initial'

import Introduction from '../components/Introduction/introduction'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [videoIntroShown, setVideoIntroShown] = useState(false)
  return (
    <div className={styles.container}>
      <Head>
        <title>Arre-Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className={styles.main}>
        {!videoIntroShown ? <Initial setVideoIntroShown={setVideoIntroShown} />
        :<div><Introduction />
        <Features />
        <Footer /></div> }
      </main>


    </div>
  )
}
